[migrator]
    ranges = []
    start = 0 # $MIGRATION_START
    stop = 0 # $MIGRATION_STOP
    tableNames = [ # $MIGRATION_TABLE_NAMES
        "eth.log_cids.repair"
    ]
    workersPerTable = 10 # $MIGRATION_WORKERS_PER_TABLE
    autoRange = true # $MIGRATION_AUTO_RANGE
    segmentSize = 10000 # $MIGRATION_AUTO_RANGE_SEGMENT_SIZE
    transferTableName = "v2db_public_blocks" # $TRANSFER_TABLE_NAME
    pagesPerTx = 1000 # $TRANSFER_SEGMENT_SIZE
    segmentOffset = 0 # $TRANSFER_SEGMENT_OFFSET
    maxPage = 0 # $TRANSFER_MAX_PAGE

[log]
    file = "logfile.txt" # $LOGRUS_FILE
    level = "info" # $LOGRUS_LEVEL
    readGapsDir = "./readGaps/" # $LOG_READ_GAPS_DIR
    writeGapsDir = "./writeGaps/" # $LOG_WRITE_GAPS_DIR
    transferGapDir = "./transferGaps/" # $LOG_TRANSFER_GAPS_DIR

[old]
    databaseName = "vulcanize_v2" # $OLD_DATABASE_NAME
    databaseHostName = "localhost" # $OLD_DATABASE_HOSTNAME
    databasePort = "5432" # $OLD_DATABASE_PORT
    databaseUser = "postgres" # $OLD_DATABASE_USER
    databasePassword = "" # $OLD_DATABASE_PASSWORD
    databaseMaxIdleConns = 0 # $OLD_DATABASE_MAX_IDLE_CONNECTIONS
    databaseMaxOpenConns = 0 # $OLD_DATABASE_MAX_OPEN_CONNECTIONS
    databaseMaxConnLifetime = 0 # $OLD_DATABASE_MAX_CONN_LIFETIME

[new]
    databaseName = "vulcanize_v3" # $NEW_DATABASE_NAME
    databaseHostName = "localhost" # $NEW_DATABASE_HOSTNAME
    databasePort = "5432" # $NEW_DATABASE_PORT
    databaseUser = "postgres" # $NEW_DATABASE_USER
    databasePassword = "" # $NEW_DATABASE_PASSWORD
    databaseMaxIdleConns = 0 # $NEW_DATABASE_MAX_IDLE_CONNECTIONS
    databaseMaxOpenConns = 0 # $NEW_DATABASE_MAX_OPEN_CONNECTIONS
    databaseMaxConnLifetime = 0 # $NEW_DATABASE_MAX_CONN_LIFETIME
